project:
  type: website
  resources:
    - "google9541c230ce597c09.html"
    - "_site/cv/*"


website:
  site-url: "https://follhim.net"
  favicon: images/spectrum-pulse.svg
  google-analytics: G-4B73YXR349
  title: Seungju Kim
  description: "Seungju Kim's research website focusing on modeling the relationship between religiousness/spirituality and health, LGBTQ+ communities, and mental health. Clinical psychology researcher at University of Illinois Urbana-Champaign (UIUC)."
  image: "images/headshot.png"
  twitter-card: true
  open-graph: true
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: research/papers.qmd
      text: Research
    - href: resource.qmd
      text: Resources
    - href: about.qmd
      text: About Me
  comments:
    giscus:
      repo: follhim/follhim.github.io
      theme: dark

format:
  html:
    # page-layout: full
    toc: true
    theme: superhero
    include-in-header:
      - person-schema.html