name: Update Scholar Stats
on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install packages
      run: |
        install.packages(c("httr", "jsonlite", "dplyr", "ggplot2", "ggiraph", "patchwork", "here"))
      shell: Rscript {0}
      
    - name: Render with SerpApi
      env:
        SERPAPI_KEY: ${{  SERPAPI_KEY }}
      run: |
        quarto render research/papers.qmd
      
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update scholar stats $(date)" || exit 0
        git push